swagger: "2.0"
info:
  version: "1.0.0"
  title: "E-Commerce API"
  description: "API for managing brands, products, and user cart"
host: "localhost:3000"
schemes:
  - "http"
basePath: "/api"
produces:
  - "application/json"
paths:
  /brands:
    get:
      summary: "Get all brands"
      responses:
        200:
          description: "A list of brands"

  /brands/{id}/products:
    get:
      summary: "Get products for a specific brand"
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: "A list of products for the brand"

  /products:
    get:
      summary: "Get all products"
      responses:
        200:
          description: "A list of products"

  /login:
    post:
      summary: "User login"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: "Successful login"

  /me/cart:
    get:
      summary: "Get user cart"
      responses:
        200:
          description: "User cart details"
    post:
      summary: "Add a product to the cart"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
      responses:
        200:
          description: "Product added to cart"

  /me/cart/{productId}:
    delete:
      summary: "Remove a product from the cart"
      parameters:
        - name: productId
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Product removed from cart"
    post:
      summary: "Change the quantity of a product in the cart"
      parameters:
        - name: productId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              quantity:
                type: integer
      responses:
        200:
          description: "Quantity updated"
